### ISSUE TITLE
Exception: Could not find at URL https://www.languagetool.org/download/LanguageTool-5.4.zip.

### ISSUE THREAD

**Issue by PS-AI** [jxmorris12/language_tool_python#48] opened 2021-11-22 12:56 UTC
Hi,

When trying to initialize Language Tool in Python code;
tool = language_tool_python.LanguageTool('en-UK'),

the following exception is raised.
Exception: Could not find at URL https://www.languagetool.org/download/LanguageTool-5.4.zip.

what is the work-around for this?

**Comment by rennenc** [comment] 2021-11-22 13:36
We are having the same issue. The docker image won't start in production.
We install latest stable upon image build, and then at runtime it's searching for 5.4, because this value is hardcoded.

Seems like the server started to return 403:
```  if req.status_code == 403: # Not found on AWS ```

Perhaps just change the code to:
```    if req.status_code != 200:  # not succeed with```

**Comment by jxmorris12** [comment] 2021-11-22 13:57
So sorry about this! I just pushed a new version (@PS-AI @rennenc) that bumps the version number to 5.5. Any idea how I can avoid this problem next time?

**Comment by rennenc** [comment] 2021-11-22 14:24
1. I suspect that the problem is that it fails to download this url from AWS: https://www.languagetool.org/download/LanguageTool-5.4.zip. Perhaps there's an issue is that 5.4 is no longer exposed when accessing from AWS?

2. We install the pre-requisite using this script:
https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh

We could have solved it by using versioned scripts (install_5-4.sh, install_5-5.sh, etc.).
This way it won't bump automatically when you release, and our docker image will always be persistent.

**Comment by jxmorris12** [comment] 2021-11-22 14:54
Ok, this is really weird. (Also seems to be an issue with LanguageTool, not language_tool_python.)

This happens from any AWS server?

**Comment by jxmorris12** [comment] 2021-11-22 14:55
You could try posting on the LT forum: https://forum.languagetool.org/

**Comment by iliasmiraoui** [comment] 2021-11-22 17:32
It fails locally as well on my end (with both the new and the old language_tool_python) while downloading works in the browser.

**Comment by jxmorris12** [comment] 2021-11-22 18:08
Thanks. So the meat of the issue is that automated dowloads fail, via something like `wget 'https://languagetool.org/download/LanguageTool-stable.zip'` or from the python interpreter:
```python
>>> import requests
>>> url = 'https://www.languagetool.org/download/LanguageTool-5.5.zip'
>>> requests.get(url)
<Response [403]>
```

**Comment by rennenc** [comment] 2021-11-23 08:37
Seems to be fixed now

**Comment by jxmorris12** [comment] 2021-11-23 18:43
Thanks! This was scary.

**Comment by AlphaMoury** [comment] 2021-11-28 23:13
I'm getting the same issue for Mac M1 on Safari 15.1

Could it be related with the user agents?

On Linux Mint, Brave Browser seems to work fine.

**Comment by PS-AI** [comment] 2021-11-29 04:57
@jxmorris12  The same error resurfaced again today. Is there a way to have the contents locally so that we do not depend on LT's server?

**Comment by jxmorris12** [comment] 2021-11-29 15:06
Huh. I just checked and the download worked fine for me. It does seem like a user agent issue, but it's only intermittent. I'll reopen this while we track down the issue.

**Comment by jxmorris12** [comment] 2022-01-05 01:48
Intermittent downloading issues seem fixed for now.

**Closed by jxmorris12** 2022-01-05 01:48 UTC
